# Generated by Django 4.2.16 on 2024-12-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'Данные покупки', 'verbose_name_plural': 'Данные покупки'},
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_line_2',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card_courier', 'Картой курьеру'), ('card_online', 'Картой онлайн')], max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
