# Generated by Django 4.2.16 on 2024-12-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_taggeditem_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-price'], 'verbose_name': 'Курсы', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AddField(
            model_name='item',
            name='base_education',
            field=models.CharField(choices=[('SPO', 'Среднее профессиональное образование'), ('VO', 'Высшее образование')], default='VO', max_length=3, verbose_name='Образование на базе'),
        ),
        migrations.AddField(
            model_name='item',
            name='duration',
            field=models.CharField(default='100', max_length=100, verbose_name='Срок обучения'),
        ),
    ]
